Root forms
FanVoice/client pull request #1
Opened 2023-04-03 18:54 UTC by Nika414

RootForms component, context with Telegram file, VideoChatForm UI + validation

2023-04-04 07:43 UTC, GuVictory requested changes

2023-04-04 07:43 UTC, GuVictory commented on src/contexts/rootContext.tsx
> +export const RootContext = createContext<GlobalContent>({
Давай обзовем это TgWebAppContext, кажется, его мы будем только для этого использовать

2023-04-04 07:43 UTC, GuVictory commented on src/pages/Forms/RootForm.tsx
> +        <Outlet />
А как же завернуть в Provider?

2023-04-04 07:43 UTC, GuVictory commented on src/pages/Forms/VideoChatForm.tsx
> +        console.log(data);
Логи убирай при создании ПР

2023-04-04 07:43 UTC, GuVictory commented on src/pages/Forms/VideoChatForm.tsx
> +                <Heading as='h2' size='md' mb={'25px'} mt='15px'>Создать видеочат</Heading>
Все тексты, вынеси в объект над компонентом и используй по ключу, например:
```
const strings = {
  'title': 'Создать видеочат',
}
```

Обращаешься потом `{strings.title}`

2023-04-04 07:43 UTC, GuVictory commented on src/pages/Forms/VideoChatForm.tsx
> +                <Heading as='h2' size='md' mb={'25px'} mt='15px'>Создать видеочат</Heading>
Это относится ко всем текстам

2023-04-04 07:43 UTC, GuVictory commented on src/pages/Forms/VideoChatForm.tsx
> +                        min={new Date().toISOString().slice(0, 16)}
Вынеси это в переменную в компоненте этом

2023-04-04 07:43 UTC, GuVictory commented on src/pages/Root.tsx
> +            <Container
Какой у тебя автоматический форматер стоит?

2023-04-04 07:43 UTC, GuVictory commented on src/utils/router.tsx
> +                // {
Коменты если не нужны - просто убирай

2023-04-04 07:43 UTC, GuVictory commented on src/utils/styles.tsx
> +export const formBoxStyles = {
Кажется, эти стили нужны только для страниц с формами + рекомендую как обычно накинуть классы и сделать в папке `src/pages/forms` файл 'forms.css`

2023-04-04 07:43 UTC, GuVictory commented on src/utils/styles.tsx
> +  minHeight: 'calc(100vh - 32px)'
Что за магия?

2023-04-04 21:27 UTC, Nika414 commented on src/contexts/rootContext.tsx
> +export const RootContext = createContext<GlobalContent>({
+

2023-04-04 21:28 UTC, Nika414 commented on src/pages/Forms/RootForm.tsx
> +        <Outlet />
++

2023-04-04 21:28 UTC, Nika414 commented on src/pages/Forms/VideoChatForm.tsx
> +        console.log(data);
++

2023-04-05 06:46 UTC, Nika414 commented on src/utils/router.tsx
> +                // {
++

2023-04-05 07:25 UTC, Nika414 commented on src/utils/styles.tsx
> +export const formBoxStyles = {
++

2023-04-05 07:38 UTC, Nika414 commented on src/pages/Root.tsx
> +            <Container
++

2023-04-05 07:41 UTC, Nika414 commented on src/utils/styles.tsx
> +  minHeight: 'calc(100vh - 32px)'
Нужно чтобы форма умещалась на странице в высоту и не было прокрутки вниз.
Поэтому я ее сделала высотой 100vh, но там есть падинги у основного блока main. Я их вычла так)

2023-04-05 07:43 UTC, Nika414 commented on src/pages/Forms/VideoChatForm.tsx
> +                        min={new Date().toISOString().slice(0, 16)}
++

2023-04-05 08:25 UTC, Nika414 commented on src/pages/Forms/VideoChatForm.tsx
> +                <Heading as='h2' size='md' mb={'25px'} mt='15px'>Создать видеочат</Heading>
++

2023-04-05 10:22 UTC, GuVictory approved these changes

2023-04-05 10:52 UTC, merged