Club page
FanVoice/client pull request #16
Opened 2023-04-25 06:31 UTC by Nika414

Страница Клуба (верстка)
Фильтрация (верстка)
Тестовое подключение к бэку (запрос спортсменов по id)

2023-04-27 10:38 UTC, GuVictory requested changes

2023-04-27 10:38 UTC, GuVictory commented on src/components/FilterPopup/FilterPopup.tsx
> +                    Умный поиск
Та же история с текстами, выноси их в объект, чтобы потом править было проще

2023-04-27 10:38 UTC, GuVictory commented on src/components/FilterPopup/FilterPopup.tsx
> +                <ModalBody p="31px">
Что за магия из 31го пикселя?

2023-04-27 10:38 UTC, GuVictory commented on src/components/FilterPopup/FilterPopup.tsx
> +                    <HStack sx={checkBoxContainerStyles} pb="26px !important">
Еще и с !important, на сколько это необходимо? Вынеси в константу и напиши коммент почему

2023-04-27 10:38 UTC, GuVictory commented on src/components/FilterPopup/FilterPopup.tsx
> +                    <Button
Эта кнопка везде будет с одинаковым дизайном, вынеси в отдельный компонент

2023-04-27 10:38 UTC, GuVictory commented on src/pages/Club/Club.tsx
> +                    alt="Название клуба"
Так же в объект, для дальнейшей простоты перехода на бек

2023-04-27 10:38 UTC, GuVictory commented on src/pages/Club/Club.tsx
> +                            {personData.map((card) => {
Вынеси в компонент отрисовки списка, это будет много где

2023-04-27 10:38 UTC, GuVictory commented on src/pages/Main/Main.tsx
> +            {isFilterOpen ? (
Можно короче:
`{isFilterOpen && <FilterPopup isOpen={isOpen} onClose={onClose} />}`

2023-04-27 10:38 UTC, GuVictory commented on src/pages/People.tsx
> +            {personData.map((card: any) => {
что за any, где тип?

2023-04-27 10:38 UTC, GuVictory commented on src/utils/api.ts
> +  getPersonInfo() {
Типизируй тут то, что возвращает функция после обращения к Api

2023-04-27 15:30 UTC, Nika414 commented on src/components/FilterPopup/FilterPopup.tsx
> +                    Умный поиск
++

2023-04-27 15:54 UTC, Nika414 commented on src/components/FilterPopup/FilterPopup.tsx
> +                    <Button
++

2023-04-28 08:47 UTC, Nika414 commented on src/components/FilterPopup/FilterPopup.tsx
> +                    <HStack sx={checkBoxContainerStyles} pb="26px !important">
++

2023-04-28 13:02 UTC, Nika414 commented on src/pages/Club/Club.tsx
> +                            {personData.map((card) => {
++

2023-04-28 13:06 UTC, Nika414 commented on src/pages/People.tsx
> +            {personData.map((card: any) => {
++

2023-04-29 10:50 UTC, GuVictory approved these changes

2023-04-29 11:48 UTC, merged