Controllers
FanVoice/client pull request #20
Opened 2023-05-04 20:31 UTC by Nika414

Добавлены ручки /categories
/categories/:id
+ исправлено картинка должна подстраиваться под размер карточки
+ добавлены key пропсы

2023-05-05 04:57 UTC, GuVictory requested changes

2023-05-05 04:57 UTC, GuVictory commented on src/components/PersonCard/PersonCard.tsx
> +        if (location.pathname === '/categories/athletes') {
А почему тут нельзя использовать navigate(`${location.pathname}/${data.id}`)? Зачем if?

2023-05-05 04:57 UTC, GuVictory commented on src/components/PersonCard/PersonCard.tsx
> +export const PersonCard = ({data}: any) => {
Почему any,  а не тип?

2023-05-05 04:57 UTC, GuVictory commented on src/components/PersonCard/PersonCard.tsx
> +                {JSON.stringify(data.name)}
Зачем? Там ведь строка должна быть

2023-05-05 04:57 UTC, GuVictory commented on src/pages/Clubs/Clubs.tsx
> +                    console.log(res);
`console` убирай в пр

2023-05-05 04:57 UTC, GuVictory commented on src/pages/Clubs/Clubs.tsx
> +            .catch((err) => console.log(err));
тут раз уж ошибка делай не console.log, а console.error

2023-05-05 04:57 UTC, GuVictory commented on src/pages/Clubs/Clubs.tsx
> +                {clubs?.map((card) => {
Если массив clubs пустой, надо рисовать заглушку по типу "Клубы не найдены"

2023-05-05 04:57 UTC, GuVictory commented on src/pages/Clubs/Clubs.tsx
>                              onClick={() => {
Вынеси в колбек, а не создавай заново для каждой карточки

2023-05-05 04:57 UTC, GuVictory commented on src/pages/Main/Main.tsx
> +            .catch((err) => console.log(err));
Тут тоже console.error

2023-05-05 04:57 UTC, GuVictory commented on src/pages/Main/Main.tsx
> +                        {categories?.map((card) => {
Тут, возможно стоит подумать о лоадере, когда у нас еще нет категорий

2023-05-05 04:57 UTC, GuVictory commented on src/pages/People.tsx
> +            .catch((err) => console.log(err));
console.error

2023-05-05 04:57 UTC, GuVictory commented on src/pages/People.tsx
> +                    console.log(res);
лог убираем

2023-05-05 04:57 UTC, GuVictory commented on src/pages/Sports/Sports.tsx
> +        api.getCategory('sports')
Тут те же комменты про консоль

2023-05-05 04:57 UTC, GuVictory commented on src/pages/Sports/Sports.tsx
> +                {sports?.map((sport) => {
Пустота и загрузка

2023-05-05 04:57 UTC, GuVictory commented on src/utils/MockData.tsx
>          id: 1,
Нам нужен этот файл еще?

2023-05-05 04:57 UTC, GuVictory commented on src/utils/api.ts
> +      .catch((err) => console.log(err));
пиши в console.error

2023-05-05 04:57 UTC, GuVictory commented on src/utils/api.ts
> +      .catch((err) => console.log(err));
пиши в console.error

2023-05-05 06:06 UTC, Nika414 commented on src/components/PersonCard/PersonCard.tsx
> +        if (location.pathname === '/categories/athletes') {
++

2023-05-05 06:07 UTC, Nika414 commented on src/components/PersonCard/PersonCard.tsx
> +                {JSON.stringify(data.name)}
++

2023-05-05 06:10 UTC, Nika414 commented on src/pages/Clubs/Clubs.tsx
> +            .catch((err) => console.log(err));
++

2023-05-05 06:10 UTC, Nika414 commented on src/pages/Main/Main.tsx
> +            .catch((err) => console.log(err));
++

2023-05-05 06:10 UTC, Nika414 commented on src/pages/People.tsx
> +            .catch((err) => console.log(err));
++

2023-05-05 06:10 UTC, Nika414 commented on src/pages/People.tsx
> +                    console.log(res);
++

2023-05-05 06:11 UTC, Nika414 commented on src/pages/Sports/Sports.tsx
> +        api.getCategory('sports')
++

2023-05-05 06:11 UTC, Nika414 commented on src/utils/api.ts
> +      .catch((err) => console.log(err));
++

2023-05-05 06:11 UTC, Nika414 commented on src/utils/api.ts
> +      .catch((err) => console.log(err));
++

2023-05-05 06:34 UTC, Nika414 commented on src/components/PersonCard/PersonCard.tsx
> +export const PersonCard = ({data}: any) => {
++

2023-05-05 07:00 UTC, Nika414 commented on src/pages/Clubs/Clubs.tsx
>                              onClick={() => {
++

2023-05-05 08:03 UTC, Nika414 commented on src/pages/Main/Main.tsx
> +                        {categories?.map((card) => {
++

2023-05-05 19:07 UTC, Nika414 commented on src/pages/Clubs/Clubs.tsx
> +                {clubs?.map((card) => {
++

2023-05-05 19:08 UTC, Nika414 commented on src/pages/Sports/Sports.tsx
> +                {sports?.map((sport) => {
++

2023-05-05 19:08 UTC, Nika414 commented on src/utils/MockData.tsx
>          id: 1,
пока да

2023-05-05 21:14 UTC, Nika414 commented
Добавлены ручки:
/v1/clubs/:id/athletes
/v1/clubs/:id/bloggers

2023-05-08 06:12 UTC, GuVictory approved these changes

2023-05-08 06:13 UTC, merged